import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-cover bg-center flex flex-col justify-center items-center p-3 md:p-8 w-full h-screen`}>{children}</body>
    </html>
  )
}
